### ISSUE TITLE
Sreeja's Performance Task Scoring Checklist 1

### ISSUE THREAD

**Issue by sreejagangapuram** [sreejagangapuram/Sreeja-Gangapuram#27]
**Submission 1** 
I checked the "row" box if I initially thought they got the point. This isn't college board's scoring. 
- [ ] Row 1: Program Purpose and Function
  - [ ] video - input, output, program function 
  - [x] written - purpose, functionality, input, output
- [x] Row 2: Data Abstraction
  - [x] written - both program code segments, data in list=fullfill purpose, identify the name of the variable, describe data 
- [x] Row 3: Managing Complexity 
  - [x] written - list managing complexity + explanation 
- [x] Row 4: Procedural Abstraction 
  - [x] written - procedure with parameter, it being called, explain the procedure 
- [x] Row 5: Algorithm Implementation 
  - [x] written - sequencing, selection, iteration, explanation of the algorithm 
- [x] Row 6: Testing 
  - [x] written - two calls, conditions tested, results 

**Submission 2**
- [ ] Row 1: Program Purpose and Function
  - [ ] video - input, output, program function 
  - [x] written - purpose, functionality, input, output
- [x] Row 2: Data Abstraction
  - [x] written - both program code segments, data in list=fullfill purpose, identify the name of the variable, describe data 
- [x] Row 3: Managing Complexity 
  - [x] written - list managing complexity + explanation 
- [x] Row 4: Procedural Abstraction 
  - [x] written - procedure with parameter, it being called, explain the procedure 
- [x] Row 5: Algorithm Implementation 
  - [x] written - sequencing, selection, iteration, explanation of the algorithm 
- [x] Row 6: Testing 
  - [x] written - two calls, conditions tested, results
